spring:
  application:
    name: api-gateway
server:
  port: 50001
  ssl:
    key-store: classpath:server.keystore
    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#Hystrix超时时间: 默认1秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 20000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2

zuul:
#  host:
#    connect-timeout-millis: 30000
#    socket-timeout-millis: 30000
  routes:
    user:
      path: /provider/**
      serviceId: provider-service
#      url: http://localhost:20001
      stripPrefix: false
    admin:
      path: /feign/**
      serviceId: feign-service
      stripPrefix: false
    order:
      path: /ribbon/**
      serviceId: ribbon-service
      stripPrefix: false