spring:
  application:
    name: config-client
  profiles:
    active: test
server:
  port: 8001
endpoints:
  sensitive: false
  health:
    sensitive: false
  metrics:
    sensitive: false
  info:
    sensitive: false
security:
  user:
    name: user
    password: password
  basic:
    path: /configprops
    enabled: true





