spring:
  application:
    name: provider-service
  jackson.serialization.indent_output: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率, 默认0.1
      percentage: 1.0
server:
  port: 20001
endpoints:
  sensitive: false
common:
  test-a: test-a
  test-b: test-b
  ops:
    accessLog: db
    errorLog: db




