spring:
  application:
    name: provider-service
server:
  port: 20001
eureka:
  client:
    healthcheck:
      enabled: true
#  ssl:
#    key-store: classpath:server.keystore
#    key-store-password: 123456
#    #keyStoreType: PKCS12
#    keyAlias: server





