spring:
  application:
    name: feign-service
server:
  port: 40001

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 51000

#provider-service:
#  ribbon:
#    listOfServers: localhost:18443
