spring:
  application:
    name: eureka-server
server:
  port: 10002
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://h3:10003/eureka/
  instance:
    hostname: h2