spring:
  application.name: config-server
  cloud.config.enabled: true
#开启本地配置
#  profiles.active: native
#  cloud.config.server.native.searchLocations: classpath:/config
#默认使用git配置
  cloud.config.server.git.uri: https://github.com/jixuju/spring-cloud-test
  cloud.config.server.git.searchPaths: /config-repo
  cloud.config.server.git.username: user
  cloud.config.server.git.password: password
server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}


